---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-autoscaler-cloud-config
  namespace: kube-system
type: Opaque
stringData:
  cloud-config: |-
    [global]
    linode-token=55b4c52123462dk23sa165cc3dba1234123125666f1422c8
    lke-cluster-id=12345
    defaut-min-size-per-linode-type=1
    defaut-max-size-per-linode-type=10
    do-not-import-pool-id=19462
    do-not-import-pool-id=19763

    [nodegroup "g6-standard-1"]
    min-size=2
    max-size=5

    [nodegroup "g6-standard-2"]
    max-size=4

    [nodegroup "g6-standard-4"]
    max-size=2