apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-worker
spec:
  serviceName: redis-worker
  replicas: 2
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis-worker
        image: redis:6.0-alpine
        ports:
        - containerPort: 6379
          name: redis-worker
        resources:
          requests:
            cpu: 100m
            memory: 50Mi

