apiVersion: v1
kind: Pod
metadata:
  name: ycsb
spec:
  containers:
    - name: ycsb
      image: 0track/ycsb:latest
      imagePullPolicy: Always
      ports:
        - name: ycsb
          containerPort: 80
          protocol: TCP
