apiVersion: apps/v1
kind: Deployment
metadata:
  name: lr-training
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lr-training
  template:
    metadata:
      labels:
        app: lr-training
    spec:
      containers:
      - name: lr-training
        image: zhaoneil/lr_training_test:var_workload
