apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-master
spec:
  serviceName: redis-master
  replicas: 2
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis-master
        image: redis:6.0-alpine
        ports:
        - containerPort: 6379
          name: redis-master
        resources:
          requests:
            cpu: 1500m
            memory: 5000Mi
---
apiVersion: v1
kind: Service
metadata:
  name: redis-master
spec:
  clusterIP: None
  ports:
    - port: 6379
      targetPort: 6379 
  selector:
      app: redis
