apiVersion: v1
kind: Pod
metadata:
  name: ycsb
  labels:
    app: test
spec:
  containers:
    - name: ycsb
      image: 0track/ycsb:latest
      imagePullPolicy: Always
      ports:
        - name: ycsb
          containerPort: 80
          protocol: TCP
      securityContext:
        capabilities:
          add:
          - SYS_PTRACE
      env:
        - name: ycsb
          value: "ycsb"

